import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@repo/ui/context/ThemeContext";
import { AuthProvider } from "@/context/AuthProvider";
import { Toaster } from "@repo/ui/components/ui/sonner";
import { RecoilContextProvider } from "@/context/RecoilContextProvider";
import "@repo/ui/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-background text-black dark:text-white">
      <body className={inter.className}>
        <ThemeProvider>
          <AuthProvider>
            <RecoilContextProvider>
              {children}
            </RecoilContextProvider>
          </AuthProvider>
          <Toaster richColors />
        </ThemeProvider>
      </body>
    </html>
  );
}
